FORMAT: 1A
HOST: http://userwho.apiblueprint.org/

# UserWho

Simple API for user CRUD.


# Group Persons

There are two kinds of persons , physical and firm persons. 

## FirmPersons Collection [/firmpersons]

### List All Firms [GET]

+ Response 200 (application/json)

        [
            {
                "id" : "5a003b78-409e-4452-b456-a6f0dcee05bd",
                "name": "Lorea Gardening S.A."
            }
        ]

### Create a New Firm [POST]

Create a new company.

+ Request (application/json)

        {
            "name": "Lorea Gardening S.A."
        }

+ Response 201 (application/json)

    + Headers

            Location: /firmpersons/5a003b78-409e-4452-b456-a6f0dcee05bd

    + Body

            {
                "id" : "5a003b78-409e-4452-b456-a6f0dcee05bd",            
                "name": "Lorea Gardening S.A."
            }
            
## PhysicalPersons Collection [/physicalpersons]

### List All Physical Persons [GET]

+ Response 200 (application/json)

        [
            {
                "id" : "5a003b78-409e-4452-b456-a6f0dcee05bd",            
                "name": "Oscar",
                "surname": "Trump",
                "secondsurname": "Garcia" 
            }
        ]

### Create a New Physical Person [POST]

Create a new physical person.

+ Request (application/json)

        {
            "name": "Oscar",
            "surname": "Trump",
            "secondsurname": "Garcia"            
        }

+ Response 201 (application/json)

    + Headers

            Location: /physicalpersons/5a003b78-409e-4452-b456-a6f0dcee05bd

    + Body

            {
                "id" : "5a003b78-409e-4452-b456-a6f0dcee05bd", 
                "name": "Oscar",
                "surname": "Trump",
                "secondsurname": "Garcia" 
            }
            
## FirmPerson Status [/firmpersons/{person_id}]


Use the FirmPerson status resource to interrogate various aspects of a firm.

+ Parameters

    + person_id: `5a003b78-409e-4452-b456-a6f0dcee05bd` (string) - The id of the person.
    
    
### Get Firm Person Details [GET]

Query the details of a firm person.

+ Response 200 (application/json)

        {
            "id" : "5a003b78-409e-4452-b456-a6f0dcee05bd",
            "name": "Lorea Gardening S.A."
        }
        

## PhysicalPerson Status [/physicalpersons/{person_id}]


Use the PhysicalPerson status resource to interrogate various aspects of a physical person.

+ Parameters

    + person_id: `5a003b78-409e-4452-b456-a6f0dcee05bd` (string) - The id of the person.
    
    
### Get Physical Person Details [GET]

Query the details of a firm person.

+ Response 200 (application/json)

        {
                "id" : "5a003b78-409e-4452-b456-a6f0dcee05bd", 
                "name": "Oscar",
                "surname": "Trump",
                "secondsurname": "Garcia" 
        }